import type {Metadata} from "next";
import {Inter, Geist_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/general/navbar";
import {Providers} from "@/components/Providers";
import Footer from "@/components/layouts/general/footer";

const geistSans = Inter({
	variable: "--font-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr" suppressHydrationWarning>
		<body
			className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
		>
		<Providers>
			<Navbar/>
			<main>
				{children}
			</main>
			<Footer/>
		</Providers>
		</body>
		</html>
	);
}
