export type Word = {
	slug: string;
	label: string;
	category: string;
	definition: string;
	example: string;
	likes: number;
	author: string;
	addedAt: string;
};

export const words: Word[] = [
	{
		slug: "goumin",
		label: "Goumin",
		category: "Verbe",
		definition: "Se battre, se quereller avec quelqu'un.",
		example: "Les deux gars ont commencé à goumin devant le maquis.",
		likes: 248,
		author: "KouaKouamé",
		addedAt: "2026-02-10",
	},
	{
		slug: "choco",
		label: "Choco",
		category: "Nom",
		definition: "Ami proche, frère de galère. Terme d'affection entre amis.",
		example: "Mon choco m'a aidé quand j'étais dans la galère.",
		likes: 192,
		author: "AbidjanCity",
		addedAt: "2026-02-08",
	},
	{
		slug: "boucantier",
		label: "Boucantier",
		category: "Nom",
		definition: "Personne qui fait beaucoup de bruit, qui perturbe la paix.",
		example: "Ce boucantier-là, il va nous faire expulser du quartier.",
		likes: 174,
		author: "NoFace225",
		addedAt: "2026-02-05",
	},
	{
		slug: "binguiste",
		label: "Binguiste",
		category: "Nom",
		definition: "Conducteur de moto-taxi, appelé aussi « binging ».",
		example: "J'ai pris un binguiste pour éviter les embouteillages.",
		likes: 156,
		author: "YopCity",
		addedAt: "2026-02-01",
	},
	{
		slug: "babi",
		label: "Babi",
		category: "Nom propre",
		definition: "Abréviation affectueuse d'Abidjan, utilisée avec fierté.",
		example: "On dit souvent : à Babi on ne dort jamais.",
		likes: 312,
		author: "Cocody225",
		addedAt: "2026-01-28",
	},
	{
		slug: "gouro",
		label: "Gouro",
		category: "Nom",
		definition: "Argent, monnaie. Terme générique pour désigner le cash.",
		example: "T'as le gouro pour sortir ce soir ou on reste à la maison ?",
		likes: 201,
		author: "GrandBassam",
		addedAt: "2026-01-25",
	},
	{
		slug: "dja",
		label: "Dja",
		category: "Verbe",
		definition: "Partir, s'en aller rapidement. Souvent utilisé à l'impératif.",
		example: "On dja avant que la pluie arrive.",
		likes: 143,
		author: "KouaKouamé",
		addedAt: "2026-01-22",
	},
	{
		slug: "tchatcher",
		label: "Tchatcher",
		category: "Verbe",
		definition: "Parler avec aisance pour convaincre ou séduire.",
		example: "Il a tellement tché la fille qu'elle a oublié son copain.",
		likes: 187,
		author: "AbidjanCity",
		addedAt: "2026-01-20",
	},
	{
		slug: "gbê",
		label: "Gbê",
		category: "Adjectif",
		definition: "Propre, net, bien habillé. Quelqu'un de stylé et soigné.",
		example: "Tu es trop gbê ce soir, tu vas où comme ça ?",
		likes: 229,
		author: "NoFace225",
		addedAt: "2026-01-18",
	},
	{
		slug: "zouglou",
		label: "Zouglou",
		category: "Nom",
		definition: "Genre musical ivoirien né dans les cités universitaires dans les années 90.",
		example: "Le zouglou de Magic System a mis Abidjan sur la carte mondiale.",
		likes: 165,
		author: "YopCity",
		addedAt: "2026-01-15",
	},
	{
		slug: "garba",
		label: "Garba",
		category: "Nom",
		definition: "Plat populaire à base d'attiéké et de thon frit, vendu dans les garbadromos.",
		example: "Un bon garba à 200 francs, c'est le bonheur du midi.",
		likes: 278,
		author: "Cocody225",
		addedAt: "2026-01-12",
	},
	{
		slug: "wari",
		label: "Wari",
		category: "Nom",
		definition: "Jeu de stratégie africain très populaire en Côte d'Ivoire.",
		example: "Les vieux passent leurs après-midis à jouer au wari sous le manguier.",
		likes: 134,
		author: "GrandBassam",
		addedAt: "2026-01-10",
	},
	{
		slug: "foutou",
		label: "Foutou",
		category: "Nom",
		definition: "Plat traditionnel à base d'igname ou de banane plantain pilée.",
		example: "Le foutou bangui avec la sauce graine, c'est un délice.",
		likes: 215,
		author: "KouaKouamé",
		addedAt: "2026-01-08",
	},
	{
		slug: "kpata",
		label: "Kpata",
		category: "Nom",
		definition: "Sandales en plastique bon marché, emblème du débrouillard abidjanais.",
		example: "Il portait ses kpata même pour aller à la mairie.",
		likes: 112,
		author: "AbidjanCity",
		addedAt: "2026-01-05",
	},
	{
		slug: "bleu-bleu",
		label: "Bleu-bleu",
		category: "Adjectif",
		definition: "Naïf, crédule, quelqu'un qui se laisse facilement avoir.",
		example: "Tu as cru ce qu'il t'a dit ? Tu es vraiment bleu-bleu.",
		likes: 198,
		author: "NoFace225",
		addedAt: "2025-12-28",
	},
	{
		slug: "dossier",
		label: "Dossier",
		category: "Nom",
		definition: "Personne très compétente dans un domaine, un expert reconnu.",
		example: "Ce gars-là est un vrai dossier en informatique.",
		likes: 241,
		author: "YopCity",
		addedAt: "2025-12-20",
	},
	{
		slug: "kpô",
		label: "Kpô",
		category: "Adjectif",
		definition: "Mort, fini, hors d'usage. Peut s'appliquer à une personne, un objet ou une situation.",
		example: "Mon téléphone est kpô, il est tombé dans l'eau.",
		likes: 167,
		author: "Cocody225",
		addedAt: "2025-12-15",
	},
	{
		slug: "maquis",
		label: "Maquis",
		category: "Nom",
		definition: "Restaurant populaire en plein air, lieu de vie sociale incontournable en Côte d'Ivoire.",
		example: "On se retrouve au maquis ce soir pour fêter ça.",
		likes: 289,
		author: "GrandBassam",
		addedAt: "2025-12-10",
	},
];

